version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rent
    volumes:
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports: 
     - 6379:6379
    restart: always

  # app:
  #   build: .
  #   container_name: rent
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
